### PR TITLE
Fixed assertion regarding accessing verification route for different user

### LINKED ISSUE #11: Incorrect assertion
Thanks for putting this together. saved me a lot of time.
### Environment
- Laravel Version: 5.7.

- PHP Version: PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:44) ( NTS )

### Description:
testUserCannotVereifyOthers() fails on a correct redirect assertion

### Steps To Reproduce:
```
 public function testUserCannotVerifyOthers()
    {
        $user = factory(User::class)->create([
            'id' => 1,
            'email_verified_at' => null,
        ]);

        $response = $this->actingAs($user)->get($this->validVerificationVerifyRoute(2));
        $response->assertRedirect($this->successfulVerificationRoute());
        // Should be ???
        // $response->assertForbidden();
    }
```

### PR DESCRIPTION
**Pull request by DCzajkowski**
Fixes #11.

### CODE REVIEW

**Comment by Ariestattoo** [comment]
You forgot to assign the $user2 variable returned from the factory.

**Comment by DCzajkowski** [comment]
Shit

**Comment by DCzajkowski** [comment]
I am so embarrassed right now. Fixed in [5.7.15](https://github.com/DCzajkowski/auth-tests/releases/tag/5.7.15)

**Comment by Ariestattoo** [comment]
Isn't it like 2am in Poland on Friday night?
You are doing better than I would :tada:

**Comment by DCzajkowski** [comment]
That is correct. I have verified it now and it works. Sorry for the inconvenience and, again, thanks for reporting. 

I'd be better off to sleep now. Cheers 😉

**Comment by drbyte** [comment]
@DCzajkowski thanks for your dedication! 👍

**Pull request merged**
